version: '3.8'

services:
  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./react-frontend/public:/tmp
    ports:
      - "80:80"
    depends_on:
      - react-frontend
    restart: unless-stopped
    networks:
      - app-network

  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraftdata:/data
      - /home/Minecraft/plugins:/plugins
      - /home/Minecraft/mods:/mods
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      OPS: "BlzingPeacck"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true

networks:
  app-network:
    driver: bridge
