version: '3.8'

services:
  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - react-frontend
    restart: unless-stopped

